ALTER TABLE `streams` ADD `tvgid` VARCHAR( 200 ) NOT NULL AFTER `streamurl3` ,
ADD `streamurl3` VARCHAR( 255 ) NOT NULL AFTER `streamurl4` ,
ADD `streamurl4` VARCHAR( 255 ) NOT NULL AFTER `streamurl5` ,
ADD `streamurl5` VARCHAR( 255 ) NOT NULL AFTER `streamurl6` ,
ADD `streamurl6` VARCHAR( 255 ) NOT NULL AFTER `streamurl7` ,
ADD `streamurl7` VARCHAR( 255 ) NOT NULL AFTER `streamurl8` ,
ADD `streamurl8` VARCHAR( 255 ) NOT NULL AFTER `streamurl9` ,
ADD `streamurl9` VARCHAR( 255 ) NOT NULL AFTER `streamurl10` ,
ADD `tvglogo` VARCHAR( 200 ) NOT NULL AFTER `tvgid` ,
ADD `tvgname` VARCHAR( 200 ) NOT NULL AFTER `tvglogo` ,
ADD `grouptitle` VARCHAR( 200 ) NOT NULL AFTER `tvgname` ;
